services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=http://localhost:8501
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend-flask:
    build: 
      context: ../lang-portal/backend-flask
    ports:
      - "5000:5000"
    volumes:
      - ../lang-portal/backend-flask:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PIP_DEFAULT_TIMEOUT=100
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PIP_NO_CACHE_DIR=1
    command: flask run --host=0.0.0.0

  writing-practice:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - BACKEND_URL=http://backend-flask:5000
      - OLLAMA_HOST=ollama-server
      - OLLAMA_PORT=11434
      - PIP_DEFAULT_TIMEOUT=100
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PIP_NO_CACHE_DIR=1
    depends_on:
      - backend-flask
      - ollama-server

volumes:
  ollama_data:

networks:
  default:
    driver: bridge 